More heap optimization for n-panelize

diff --git a/n-kill b/n-kill
--- a/n-kill
+++ b/n-kill
@@ -7,9 +7,8 @@
 
 emulate -L zsh
 
-zmodload zsh/curses
-
 setopt extendedglob
+zmodload zsh/curses
 
 local IFS="
 "
@@ -41,7 +40,7 @@ NLIST_REMEMBER_STATE=0
 typeset -a NLIST_NONSELECTABLE_ELEMENTS
 NLIST_NONSELECTABLE_ELEMENTS=( 1 )
 
-type ps 2>/dev/null 1>&2 || { echo "Error: \`ps' not found"; return 1 }
+type ps 2>/dev/null 1>&2 || { echo >&2 "Error: \`ps' not found"; return 1 }
 
 case "$(uname)" in
     CYGWIN*) list=( `command ps -Wa` )  ;;
@@ -49,7 +48,7 @@ case "$(uname)" in
 esac
 
 # Ask of PID
-title=$'\x1b[00;31m'"${list[1]}"$'\x1b[00;00m'
+title=$'\x1b[00;31m'"${list[1]}"$'\x1b[00;00m\0'
 shift list
 list=( "$title" "${(@M)list:#(#i)*$1*}" )
 
@@ -64,7 +63,7 @@ n-list "$list[@]"
 
 # Got answer? (could be Ctrl-C or 'q')
 if [ "$REPLY" -gt 0 ]; then
-    selected="$reply[$REPLY]"
+    selected="$reply[REPLY]"
     selected="${selected## #}"
     pid="${selected%% *}"
 
@@ -72,16 +71,26 @@ if [ "$REPLY" -gt 0 ]; then
     signal_names=( ${(vin)signals} )
     typeset -a NLIST_HOP_INDEXES
     NLIST_HOP_INDEXES=( 3 6 8 )
+    unset NLIST_COLORING_PATTERN
     n-list $'\x1b[00;31mSelect signal:\x1b[00;00m' "$signal_names[@]"
 
     if [ "$REPLY" -gt 0 ]; then
-        selected="$reply[$REPLY]"
+        selected="$reply[REPLY]"
         signal="${(k)signals[(r)$selected]}"
 
-        # Will change so that the command actually
-        # executes when function is more tested
-        print -zr "kill -$signal $pid"
+        # ZLE?
+        if [ "${(t)CURSOR}" = "integer-local-special" ]; then
+            zle redisplay
+            zle kill-whole-line
+            zle -U "kill -$signal $pid"
+        else
+            print -zr "kill -$signal $pid"
+        fi
+    else
+        [ "${(t)CURSOR}" = "integer-local-special" ] && zle redisplay
     fi
+else
+    [ "${(t)CURSOR}" = "integer-local-special" ] && zle redisplay
 fi
 
 # vim: set filetype=zsh:
